### ISSUE TITLE
Fill Precedence Research

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/spool-whitepaper#8]
2. Precedence Research
    2-1. Proxy Staking - Cardano
    2-2. Passive Delegate - Tezos
    2-3. Multi-sig Staking - PIVX
    2-4. Staking Pool - vest.com
    2-5. Atomic Swap - Swingby Protocol
    2-6. Token as a Service - TaaS
    2-7. Recoverability against incident - DAI and Bancor

**Comment by syuhei176** [comment]
Cardano white paper is here https://eprint.iacr.org/2016/889.pdf. Staking Delegation is section 8.

**Comment by syuhei176** [comment]
`passive delegate`'s passive is just mark of delegate who are not make transaction in any period.
The delegate marked passive is never selected baking or endorsement.

http://doc.tzalpha.net/whitedoc/proof_of_stake.html#delegation

This is similar to the problem cardano stakeholder has.
> Stakeholder in cardano networks must be online, and this is burden for stakeholder who has small stake.

**Comment by syuhei176** [comment]
paper of the proxy signature. https://eprint.iacr.org/2003/096.pdf

**Comment by syuhei176** [comment]
Making logic..
Proxy Staking and Stake Delegation is like mining pool, but these are close to one blockchain.
Atomic Swap is one of the solution to trade cryptocurrency of different blockchain.
...
